#!/usr/bin/env bun
/**
 * make_adw — generate a new one-shot ADW script from agents in the config.
 *
 * Usage:
 *     bun <skill>/scripts/make_adw.ts --name review_docs --agents scout,builder
 *
 * Each named agent becomes one agent phase, chained by envelope. Starter agents
 * map to their concrete output types; unknown agents get GenericOutput (define a
 * concrete type in adw_modules/data_types.ts and swap it in).
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";

const OUTPUT_TYPES: Record<string, string> = {
  planner: "PlanOutput",
  builder: "BuildOutput",
  scout: "ScoutOutput",
  reviewer: "ReviewOutput",
  documenter: "DocumentOutput",
};

const HEADER = `#!/usr/bin/env bun
/**
 * ADW {title} — generated by make_adw.
 *
 * Usage:
 *     bun adws/adw_{name}.ts "<prompt or path/to/prompt.md>" [--config adws/adw_sssf_config/sssf.config.yaml] [--adw-id a1b2c3d4]
 *
 * Phases: engineer(request) -> {chain}
 */

import { parseArgs } from "node:util";

import * as agents from "./adw_modules/agents.ts";
import type { EnvelopeBase } from "./adw_modules/data_types.ts";
import { AgentCall, PhaseParams, {imports} } from "./adw_modules/data_types.ts";
import * as gates from "./adw_modules/gates.ts";
import * as session from "./adw_modules/session.ts";
import * as utils from "./adw_modules/utils.ts";

const REQUIRED_AGENTS = {agents_list};

export async function main(
  prompt: string,
  config = "adws/adw_sssf_config/sssf.config.yaml",
  adw_id?: string | null,
): Promise<number> {
  const cfg = agents.load_config(config);
  agents.validate(cfg, REQUIRED_AGENTS);
  const run = session.ensure(cfg, adw_id);

  await run.phase(
    PhaseParams({
      name: "request",
      kind: "engineer",
      owner: run.engineer,
      description: "Capture the incoming ask",
    }),
    (ph) => ph.log({ input: prompt }),
  );

  let previous: EnvelopeBase | null = null;
{phases}
  return run.finish();
}

if (import.meta.main) {
  const { values, positionals } = parseArgs({
    args: Bun.argv.slice(2),
    options: {
      config: { type: "string", default: "adws/adw_sssf_config/sssf.config.yaml" },
      "adw-id": { type: "string" },
    },
    allowPositionals: true,
  });
  await session.cli(() =>
    main(utils.resolve_prompt(positionals[0] ?? ""), values.config, values["adw-id"]),
  );
}
`;

const PHASE = `  // TODO: replace this description — say what THIS phase does and why.
  previous = await run.phase(
    PhaseParams({
      name: "{name}",
      kind: "agent",
      owner: "{agent}",
      description: "Run {agent} over the request and hand its envelope on",
    }),
    (ph) =>
      ph.call(
        AgentCall({
          output_type: {output_type},
          prompt,
          previous,
          gates: [gates.artifacts_exist],
        }),
      ),
  );
`;

function fill(template: string, values: Record<string, string>): string {
  let out = template;
  for (const [key, value] of Object.entries(values)) {
    out = out.replaceAll("{" + key + "}", value);
  }
  return out;
}

function title_case(name: string): string {
  return name
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

function main(): number {
  const { values } = parseArgs({
    args: Bun.argv.slice(2),
    options: {
      name: { type: "string" },
      agents: { type: "string" },
      force: { type: "boolean", default: false },
    },
    allowPositionals: true,
  });

  if (!values.name || !values.agents) {
    console.log("usage: make_adw.ts --name <snake_case_name> --agents <a,b,c>");
    return 1;
  }

  const agent_names = values.agents
    .split(",")
    .map((a) => a.trim())
    .filter(Boolean);
  if (!agent_names.length) {
    console.log("no agents given");
    return 1;
  }

  const types = agent_names.map((a) => OUTPUT_TYPES[a] ?? "GenericOutput");
  const seen: Record<string, number> = {};
  const phases: string[] = [];
  agent_names.forEach((agent, index) => {
    seen[agent] = (seen[agent] ?? 0) + 1;
    const phase_name = seen[agent] === 1 ? agent : `${agent}_${seen[agent]}`;
    phases.push(fill(PHASE, { name: phase_name, agent, output_type: types[index]! }));
  });

  const body = fill(HEADER, {
    title: title_case(values.name),
    name: values.name,
    chain: agent_names.join(" -> "),
    imports: [...new Set(types)].sort().join(", "),
    agents_list: JSON.stringify([...new Set(agent_names)].sort()),
    phases: phases.join("\n"),
  });

  const dest = join(process.cwd(), "adws", `adw_${values.name}.ts`);
  if (existsSync(dest) && !values.force) {
    console.log(`${dest} already exists — use --force to overwrite`);
    return 1;
  }
  mkdirSync(join(process.cwd(), "adws"), { recursive: true });
  writeFileSync(dest, body);
  console.log(`wrote ${dest}`);
  console.log(
    "next: replace each phase description — a generated one says nothing, " +
      "and the description is the only intent the trace ever shows",
  );
  console.log(`run: bun adws/adw_${values.name}.ts "your request"`);
  return 0;
}

process.exit(main());
